Repository DataDog/apps, pull requests merged in 2022-04, with the labels that each got.

#126 chore: update react-scripts to v5
  .changeset/cuddly-pugs-hammer.md
  examples/custom-widget-with-1st-party-data/package.json
  examples/custom-widget-with-3rd-party-data/package.json
  examples/geomap/datadog-app/package.json
  examples/random-dog/dog-image-widget/package.json
  examples/redis/datadog-app/package.json
  examples/sentiment/package.json
  examples/starter-kit/package.json
  examples/stream/admin/package.json
  examples/stream/ui/package.json
  package.json
  packages/create-app/src/template/package.json
  packages/framepost/__tests__/child.ts
  packages/framepost/__tests__/parent.ts
  packages/ui-extensions-react/package.json
  packages/ui-extensions-sdk/src/utils/testUtils.ts
  yarn.lock
Labels: bug, dependencies

#139 chore: remove VS Code Workspace Settings
  .gitignore
  .vscode/settings.json
Labels: enhancement

#135 [UIAPPS-181] Add Org Settings Documentation
  docs/en/getting-started.md
  docs/en/programming-model.md
Labels: documentation
